language: java

jdk:
  - oraclejdk8
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script: mvn --settings .travis/settings.xml clean verify -e

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: Hevelian/hevelian-olastic
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: Hevelian/hevelian-olastic
      tags: true
      jdk: oraclejdk8
