language: java
jdk:
  - oraclejdk8

after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSS_USERNAME}</username><password>\${env.OSS_PASSWORD}</password></server><server><id>ossrh</id><username>\${env.OSS_USERNAME}</username><password>\${env.OSS_PASSWORD}</password></server></servers><profiles><profile><id>ossrh</id><activation><activeByDefault>true</activeByDefault></activation><properties><gpg.executable>\${env.GPG_EXECUTABLE}</gpg.executable><gpg.passphrase>\${env.GPG_PASSPHRASE}</gpg.passphrase></properties></profile></profiles></settings>" > ~/travis-settings.xml
  - mvn deploy --settings ~/travis-settings.xml